apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-container
        image: budget-app_web:latest  # Make sure it's pushed to a registry or built inside the cluster
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: myapp_development
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: password

